;;; Compiled snippets and support files for `eshell'
;;; Snippet definitions:
;;;
(yas-define-snippets 'eshell
                     '(("lastdir" "/Users/andy_normann/.emacs.d/eshell\n~/Git/Code/cpp\n/Users/andy_normann/Git/Code/rust\n/Users/andy_normann/Git/Code/c\n/Users/andy_normann/Git/Code/c/hackerrank\n/Users/andy_normann/Git/Code/c/hackerrank/datastructures/linkedlist\n~/.emacs.d\n/Users/andy_normann/Git/Code/go\n/Users/andy_normann/Git/Code/go/src/halla\n/usr/local/Cellar/gtk+3\n/usr/local/Cellar/gtk+3/3.20.6/bin\n/usr/local/Cellar/gtk+3/3.20.6\n/usr/local/Cellar/gtk+3/3.20.6/include\n/usr/local/Cellar/gtk+3/3.20.6/include/gtk-3.0\n/usr/local/Cellar/gtk+3/3.20.6/include/gtk-3.0/gtk\n/Users/andy_normann/Downloads\n/Users/andy_normann/Downloads/emacs-master\n/Users/andy_normann/Git/Code/cpp\n/Users/andy_normann/Git/Code\n/Users/andy_normann/Git/Code/c/hackerrank/datastructures/linkedlist\n~/.emacs.d\n/Users/andy_normann/Git/Code/cpp/sfml/langtonant\n/Users/andy_normann/Git/Code/cpp/sfml\n/Users/andy_normann/Git/Code/cpp/sfml/android\n~\n/Users/andy_normann/Git/Code/go/src/codekata/warmup\n/Users/andy_normann/Git/Code/go/src/codekata\n/Users/andy_normann/Git/Code/go/src/codekata/implementation\n/Users/andy_normann\n/Users/andy_normann/.cargo\n/Users/andy_normann/.cargo/bin\n/Users/andy_normann\n~\n" "lastdir" nil nil nil "/Users/andy_normann/.emacs.d/eshell/lastdir" nil nil)
                       ("history" "ls\nl\ncd Git/Code/\nls\ncd cpp/\nls\n.\ncd go/\nls\ncd src/halla/\nls\nff main.go \nls\ncd\ncd Downloads/\nls\ncd emacs-master/\nls\n./configure --with-x-toolkit=gtk3 --with-xwidgets\n./configure --with-xwidgets --with-x-toolkit=gtk3\n./configure --with-xwidgets --with-x-toolkit=gtk3 -with-x\nls\nff configure.ac\nls\n./configure --with-x\n./configure --with-x --with-xwidgets\n./configure --with-x --with-x-toolkit=gtk3\n./configure --with-x --with-x-toolkit=gtk3 --with-xwidgets\nls\nff INSTALL\nls\n./configure --with-x --with-x-toolkit=gtk --with-xwidgets\n./configure --with-x --with-x-toolkit=gtk --with-xwidgets with-ns=no\n./configure --with-x --with-x-toolkit=gtk --with-xwidgets --with-ns=no\nbrew search xcb-shm\ncd\ncd /usr/local/Cellar/gtk+3/\nls\ncd 3.20.6/\nls\ncd bin\nls\n.\ncd include/\nls\ncd gtk-3.0/\nls\ncd gtk/\nls\nls\npwd\nexport GTK_LIBS=/usr/local/Cellar/gtk+3/3.20.6/include/gtk-3.0/gtk\ncd\ncd Downloads/\nls\ncd emacs-master/\nls\n./configure --with-x --with-x-toolkit=gtk --with-xwidgets --with-ns=no\n./configure --with-x --with-x-toolkit=gtk --with-xwidgets\n./configure --with-x --with-x-toolkit=gtk3 --with-xwidgets\nls\ncd\ncd Git/Code/cpp/\nls\n.\ncd c/hackerrank/datastructures/linkedlist/\nls\n./11_detectcycle \n./11_detectcycle \nls\n./11_detectcycle \n./11_detectcycle \nls\nla\nl\nls\n.\ncd android/\nls\nmake\nla\nls\nl\nls\nls\ncat hallo.c\n./halla\ncat halla.c\nclang hallo.c\n./a.out 1 2 3 4\nclang hallo.c\n./a.out 1 2 3 4\ncat hallo.c\ncat halla.c\nclang halla.c\n./a.out 1 2 3 4\nssh inf5063@oslo.mlab.no\nssh inf5063-g13@oslo.mlab.no\nls\nsimula\nssh simula\nls\ncd warmup/\nls\ncd ..\nls\ndc implementation/\nls\ncd implementation/\nls\nls\ncd\nls\nla\nexa\ncd .cargo\nls\ncd bin/\nls\ncd\nexa\nfind-files .zshrc\nfind-file .zshrc\nls\nl\nls\nfind-file halla.c\nvim halla.c\n" "history" nil nil nil "/Users/andy_normann/.emacs.d/eshell/history" nil nil)
                       ("alias" "alias ff find-file $1\nalias l ls -la1\nalias . cd ..\n" "alias" nil nil nil "/Users/andy_normann/.emacs.d/eshell/alias" nil nil)))


;;; Do not edit! File generated at Fri Oct 21 12:21:40 2016
