"type" = "blue"
"constant" = "purple"
"constant.numeric" = "purple"
"constant.character.escape" = "orange"
"string" = "green"
"string.regexp" = "orange"
"comment" = "grey"
"variable" = "fg"
"variable.builtin" = "orange"
"variable.parameter" = "fg"
"variable.other.member" = "fg"
"label" = "orange"
"punctuation" = "fg"
"punctuation.delimiter" = "fg"
"punctuation.bracket" = "fg"
"keyword" = "red"
"keyword.directive" = "purple"
"operator" = "orange"
"function" = "green"
"function.builtin" = "blue"
"function.macro" = "purple"
"tag" = "purple"
"namespace" = "blue"
"attribute" = "blue"
"constructor" = "blue"
"module" = "blue"
"special" = "orange"

"markup.heading.marker" = "grey"
"markup.heading.1" = { fg = "red", modifiers = ["italic"] }
"markup.heading.2" = { fg = "orange", modifiers = ["italic"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["italic"] }
"markup.heading.4" = { fg = "green", modifiers = ["italic"] }
"markup.heading.5" = { fg = "blue", modifiers = ["italic"] }
"markup.heading.6" = { fg = "fg", modifiers = ["italic"] }
"markup.list" = "red"
"markup." = { modifiers = ["italic"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text" = "purple"
"markup.quote" = "grey"
"markup.raw" = "green"

"diff.plus" = "green"
"diff.delta" = "orange"
"diff.minus" = "red"

"ui.background" = { bg = "bg0" }
"ui.background.separator" = "grey"
"ui.cursor" = { fg = "bg0", bg = "fg" }
"ui.cursor.match" = { modifiers = ["underlined"] }
"ui.cursor.insert" = { fg = "black", bg = "grey" }
"ui.cursor.select" = { fg = "bg0", bg = "blue" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg1" }
"ui.selection" = { bg = "bg4" }
"ui.linenr" = "grey"
"ui.linenr.selected" = "fg"
"ui.statusline" = { fg = "fg", bg = "bg3" }
"ui.statusline.inactive" = { fg = "grey", bg = "bg1" }
"ui.statusline.normal" = { fg = "bg0", bg = "green", modifiers = [""] }
"ui.statusline.insert" = { fg = "bg0", bg = "blue", modifiers = [""] }
"ui.statusline.select" = { fg = "bg0", bg = "yellow", modifiers = [""] }
"ui.bufferline" = { fg = "grey", bg = "bg1" }
"ui.bufferline.active" = { fg = "fg", bg = "bg4", modifiers = ["italic"] }
"ui.popup" = { fg = "grey", bg = "bg2" }
"ui.window" = { fg = "grey", bg = "bg0" }
"ui.help" = { fg = "fg", bg = "bg2" }
"ui.text" = "fg"
"ui.text.focus" = "green"
"ui.menu" = { fg = "fg", bg = "bg3" }
"ui.menu.selected" = { fg = "bg0", bg = "green" }
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.virtual.indent-guide" = { fg = "bg4" }
"ui.virtual.ruler" = { bg = "bg2" }

"hint" = "blue"
"info" = "green"
"warning" = "yellow"
"error" = "red"
"diagnostic" = { underlined = { style = "line" } }
"diagnostic.hint" = { underline = { color = "blue", style = "dotted" } }
"diagnostic.info" = { underline = { color = "green", style = "dotted" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

[palette]

black = "#1d232e"
bg0 = "#1d232e"
bg1 = "#33353f"
bg2 = "#363944"
bg3 = "#3b3e48"
bg4 = "#414550"
bg_red = "#8a3f45"
diff_red = "#a6333d"
bg_green = "#98c379"
diff_green = "#7db357"
bg_blue = "#61afef"
diff_blue = "#61afef"
diff_yellow = "#ebd4a9"
fg = "#dcdfe4"
red = "#e06c75"
orange = "#e5c07b"
yellow = "#e6a857"
green = "#98c379"
cyan = "#56b6c2"
blue = "#61afef"
purple = "#c678dd"
grey = "#53545c"
grey_dim = "#3a3c40"
